.TH "src/mainpage.php" 3 "Mon Aug 22 2011" "phpTiSrcLib" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mainpage.php \- 
.PP
this file contains the doc mainpage  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
this file contains the doc mainpage 

\fBAuthor:\fP
.RS 4
Claire Dune 
.RE
.PP
\fBDate:\fP
.RS 4
21/08/2011 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for phpTiSrcLib from the source code'\&.
